# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(997, 814)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_video = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_video.setGeometry(QtCore.QRect(20, 10, 961, 751))
        self.groupBox_video.setObjectName("groupBox_video")
        self.label_image = QtWidgets.QLabel(self.groupBox_video)
        self.label_image.setGeometry(QtCore.QRect(0, 30, 960, 540))
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.checkBox_enable_camera = QtWidgets.QCheckBox(self.groupBox_video)
        self.checkBox_enable_camera.setGeometry(QtCore.QRect(640, 730, 101, 22))
        self.checkBox_enable_camera.setObjectName("checkBox_enable_camera")
        self.label_processing_time = QtWidgets.QLabel(self.groupBox_video)
        self.label_processing_time.setGeometry(QtCore.QRect(850, 620, 61, 17))
        self.label_processing_time.setObjectName("label_processing_time")
        self.label_5 = QtWidgets.QLabel(self.groupBox_video)
        self.label_5.setGeometry(QtCore.QRect(730, 620, 120, 17))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_video)
        self.label_4.setGeometry(QtCore.QRect(640, 620, 67, 17))
        self.label_4.setObjectName("label_4")
        self.label_fps = QtWidgets.QLabel(self.groupBox_video)
        self.label_fps.setGeometry(QtCore.QRect(670, 620, 67, 17))
        self.label_fps.setObjectName("label_fps")
        self.label_video_status = QtWidgets.QLabel(self.groupBox_video)
        self.label_video_status.setGeometry(QtCore.QRect(830, 710, 121, 20))
        self.label_video_status.setObjectName("label_video_status")
        self.checkBox_enable_other_features = QtWidgets.QCheckBox(self.groupBox_video)
        self.checkBox_enable_other_features.setGeometry(QtCore.QRect(640, 670, 141, 22))
        self.checkBox_enable_other_features.setObjectName("checkBox_enable_other_features")
        self.pushButton_load_video = QtWidgets.QPushButton(self.groupBox_video)
        self.pushButton_load_video.setGeometry(QtCore.QRect(480, 620, 141, 27))
        self.pushButton_load_video.setObjectName("pushButton_load_video")
        self.lineEdit_path_video = QtWidgets.QLineEdit(self.groupBox_video)
        self.lineEdit_path_video.setGeometry(QtCore.QRect(90, 620, 371, 27))
        self.lineEdit_path_video.setObjectName("lineEdit_path_video")
        self.label_2 = QtWidgets.QLabel(self.groupBox_video)
        self.label_2.setGeometry(QtCore.QRect(0, 620, 91, 17))
        self.label_2.setObjectName("label_2")
        self.pushButton_load_graph = QtWidgets.QPushButton(self.groupBox_video)
        self.pushButton_load_graph.setGeometry(QtCore.QRect(480, 650, 141, 27))
        self.pushButton_load_graph.setObjectName("pushButton_load_graph")
        self.label = QtWidgets.QLabel(self.groupBox_video)
        self.label.setGeometry(QtCore.QRect(0, 650, 81, 17))
        self.label.setObjectName("label")
        self.lineEdit_path_graph = QtWidgets.QLineEdit(self.groupBox_video)
        self.lineEdit_path_graph.setGeometry(QtCore.QRect(90, 650, 371, 27))
        self.lineEdit_path_graph.setObjectName("lineEdit_path_graph")
        self.lineEdit_path_gender_model = QtWidgets.QLineEdit(self.groupBox_video)
        self.lineEdit_path_gender_model.setGeometry(QtCore.QRect(90, 680, 371, 27))
        self.lineEdit_path_gender_model.setObjectName("lineEdit_path_gender_model")
        self.pushButton_load_gender_model = QtWidgets.QPushButton(self.groupBox_video)
        self.pushButton_load_gender_model.setGeometry(QtCore.QRect(480, 680, 141, 27))
        self.pushButton_load_gender_model.setObjectName("pushButton_load_gender_model")
        self.label_3 = QtWidgets.QLabel(self.groupBox_video)
        self.label_3.setGeometry(QtCore.QRect(0, 680, 91, 17))
        self.label_3.setMidLineWidth(-4)
        self.label_3.setObjectName("label_3")
        self.lineEdit_path_age_model = QtWidgets.QLineEdit(self.groupBox_video)
        self.lineEdit_path_age_model.setGeometry(QtCore.QRect(90, 710, 371, 27))
        self.lineEdit_path_age_model.setObjectName("lineEdit_path_age_model")
        self.pushButton_load_age_model = QtWidgets.QPushButton(self.groupBox_video)
        self.pushButton_load_age_model.setGeometry(QtCore.QRect(480, 710, 151, 27))
        self.pushButton_load_age_model.setObjectName("pushButton_load_age_model")
        self.label_6 = QtWidgets.QLabel(self.groupBox_video)
        self.label_6.setGeometry(QtCore.QRect(0, 710, 81, 21))
        self.label_6.setObjectName("label_6")
        self.checkBox_enable_record = QtWidgets.QCheckBox(self.groupBox_video)
        self.checkBox_enable_record.setGeometry(QtCore.QRect(640, 650, 96, 22))
        self.checkBox_enable_record.setObjectName("checkBox_enable_record")
        self.label_cur_frame = QtWidgets.QLabel(self.groupBox_video)
        self.label_cur_frame.setGeometry(QtCore.QRect(910, 580, 47, 13))
        self.label_cur_frame.setText("")
        self.label_cur_frame.setObjectName("label_cur_frame")
        self.horizontalSlider_video = QtWidgets.QSlider(self.groupBox_video)
        self.horizontalSlider_video.setGeometry(QtCore.QRect(20, 580, 881, 22))
        self.horizontalSlider_video.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_video.setObjectName("horizontalSlider_video")
        self.checkBox_enable_detection_s3fd = QtWidgets.QCheckBox(self.groupBox_video)
        self.checkBox_enable_detection_s3fd.setGeometry(QtCore.QRect(770, 690, 171, 22))
        self.checkBox_enable_detection_s3fd.setObjectName("checkBox_enable_detection_s3fd")
        self.checkBox_enable_detection = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_enable_detection.setGeometry(QtCore.QRect(660, 700, 131, 22))
        self.checkBox_enable_detection.setObjectName("checkBox_enable_detection")
        self.checkBox_enable_playing = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_enable_playing.setGeometry(QtCore.QRect(660, 720, 101, 22))
        self.checkBox_enable_playing.setObjectName("checkBox_enable_playing")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 997, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_video.setTitle(_translate("MainWindow", "Video"))
        self.checkBox_enable_camera.setText(_translate("MainWindow", "Camera"))
        self.label_processing_time.setText(_translate("MainWindow", "--/--"))
        self.label_5.setText(_translate("MainWindow", "Processing time:"))
        self.label_4.setText(_translate("MainWindow", "FPS:"))
        self.label_fps.setText(_translate("MainWindow", "--/--"))
        self.label_video_status.setText(_translate("MainWindow", "Status"))
        self.checkBox_enable_other_features.setText(_translate("MainWindow", "Other features"))
        self.pushButton_load_video.setText(_translate("MainWindow", "Select_video"))
        self.label_2.setText(_translate("MainWindow", "Path to video"))
        self.pushButton_load_graph.setText(_translate("MainWindow", "Select_graph"))
        self.label.setText(_translate("MainWindow", "Detector"))
        self.pushButton_load_gender_model.setText(_translate("MainWindow", "Select_model"))
        self.label_3.setText(_translate("MainWindow", "Gender"))
        self.pushButton_load_age_model.setText(_translate("MainWindow", "Select_model"))
        self.label_6.setText(
            _translate("MainWindow", "<html><head/><body><p>Age</p></body></html>")
        )
        self.checkBox_enable_record.setText(_translate("MainWindow", "Record"))
        self.checkBox_enable_detection_s3fd.setText(_translate("MainWindow", "Face detector S3FD"))
        self.checkBox_enable_detection.setText(_translate("MainWindow", "Face detector"))
        self.checkBox_enable_playing.setText(_translate("MainWindow", "Play Video"))
